services:
  help-the-stars:
    build: .
    ports:
      - 1983:1983
    volumes:
      - ./db:/app/db
    env_file:
      - .env
    command:
      - "./help-the-stars"
      - "--gh-token"
      - "$GITHUB_TOKEN"
      - "--labels"
      - "$LABELS"
      - "--db-file"
      - "$DB_FILE"
      - "--matrix-server"
      - "$MATRIX_HOMESERVER"
      - "--matrix-user"
      - "$MATRIX_USERNAME"
      - "--matrix-password"
      - "$MATRIX_PASSWORD"
      - "--matrix-room"
      - "$MATRIX_ROOM_ID"
